bodies:
  - name: "משרד הכלכלה"
  - name: "משרד התחבורה והבטיחות בדרכים"
  - name: "משרד החקלאות ופיתוח הכפר"
  - name: "משרד האנרגיה והמים"
  - name: "משרד האוצר"
    department: "אגף התקציבים"
  - name: "משרד ראש הממשלה"
  - name: "הרשות להגבלים עסקיים"
keywords:
  - "ריכוזיות"
  - "אסדרה"
  - "מונופול"
  - "רגולציה"
  - "טרכטנברג"
  - "תחרות"
  - "יוקר המחיה"
  - "פיקוח על מחירים"
  - "נשר מפעלי מלט ישראליים בע\"מ"
  - "שבי רגולטורי"
  - "סוארי"
