bodies:
  - name: "בנק ישראל"
  - name: "משרד האוצר"
  - name: "משרד המשפטים"
  - name: "המשרד לביטחון הפנים"
    department: "משטרת ישראל"
  - name: "הלשכה המרכזית לסטטיסטיקה"
  - name: "רשות המיסים בישראל"
  - name: "משרד האוצר"
    department: "אגף שוק ההון, ביטוח וחסכון"
  - name: "רשות החברות הממשלתיות"
  - name: "ענבל חברה לביטוח בע\"מ"
  - name: "משרד האוצר"
    department: "אגף החשב הכללי"
  - name: "המוסד לביטוח לאומי"
  - name: "משרד הבריאות"
  - name: "נציבות שרות המדינה"
  - name: "משרד הכלכלה"
  - name: "משרד החקלאות ופיתוח הכפר"
  - name: "משרד החוץ"
  - name: "משרד התקשורת"
  - name: "משרד ראש הממשלה"
  - name: "מכון התקנים הישראלי"
  - name: "אשרא - החברה הישראלית לביטוח יצוא בע\"מ"
  - name: "משרד הרווחה והשירותים החברתיים"
  - name: "משרד החינוך"
  - name: "משרד התחבורה והבטיחות בדרכים"
  - name: "משרד התשתיות הלאומיות"
  - name: "משרד האנרגיה והמים"
  - name: "חברת החשמל לישראל בע\"מ"
  - name: "רשות לשרותים ציבוריים"
    department: "חשמל"
  - name: "משרד התרבות והספורט"
  - name: "המועצה להסדר ההימורים בספורט"
  - name: "ההתאחדות לכדורגל בישראל"
  - name: "איגוד הכדורסל בישראל"
keywords:
  - "ריכוזיות"
  - "אסדרה"
  - "מונופול"
  - "רגולציה"
  - "טרכטנברג"
  - "תחרות"
  - "יוקר המחיה"
  - "פיקוח על מחירים"
  - "נשר מפעלי מלט ישראליים בע\"מ"
  - "שבי רגולטורי"
  - "סוארי"
