bodies:
  - name: משרד הכלכלה
  - name: רשות ההגבלים העסקיים
  - name: משרד האוצר
    department: מינהל התכנון
  - name: משרד התחבורה והבטיחות בדרכים
  - name: משרד החקלאות ופיתוח הכפר
  - name: משרד התשתיות הלאומיות, האנרגיה והמים
  - name: משרד ראש הממשלה
  - name: משרד הבינוי והשיכון
  - name: רשות מקרקעי ישראל
