bodies:
  - name: "משרד הבריאות"
  - name: "הרשות הממשלתית למים ולביוב"
  - name: "מקורות חברת מים בע\"מ"
  - name: "משרד הפנים"
  - name: "התנור - תאגיד מים וביוב בע\"מ"
  - name: "המשרד להגנת הסביבה"
  - name: "רשות החברות הממשלתיות"
  - name: "חברת דואר ישראל בע\"מ"
  - name: "נתיבי אילון בע\"מ"
  - name: "משרד התחבורה והבטיחות בדרכים"
  - name: "רכבת ישראל בע\"מ"
  - name: "משרד האוצר"
  - name: "חברת נמל אשדוד בע\"מ"
  - name: "חברת נמל חיפה בע\"מ"
  - name: "חברת נמלי ישראל - פיתוח ונכסים בע\"מ"
  - name: "מקורות פיתוח וייזום בע\"מ"
  - name: "רשות שדות התעופה"
  - name: "רשות התעופה האזרחית"
keywords:
  - "תאגידי מים וביוב"
  - "מועצות מקומיות"
  - "עיריות"
  - "זיהום מים"
  - "אתרי קידוח"
  - "חיטוי"
  - "מתקן מונע זרימה חוזרת (מז\"ח)"
  - "תכנית דיגום"
  - "הרתחה"
  - "טיהור שפכים"
  - "קולחים"
  - "אקוויפט החוף"
  - "תכנית אב"
  - "מי תהום"
  - "משק המים"
  - "שאיבת יתר"
  - "ועדת ביין"
  - "שירות הידרולוגי"
  - "כח אדם"
  - "פיצויים"
  - "מכרזים"
  - "קרובי משפחה"
  - "דירקטוריון"
  - "שכר"
  - "התקשרויות"
  - "חוק חובת המכרזים"
  - "ממשל תאגידי"
  - "תקצוב"
  - "ביקורת פנים"
  - "כבישים"
  - "תחזוקה"
  - "תחבורה ציבורית"
  - "בטיחות"
  - "מיקור חוץ"
  - "אסדרה"
  - "קרונועים"
  - "קו הרכבת ת\"א-ירושלים"
  - "תשלומי העברה (סובסידיה)"
  - "מסילה"
  - "אשפה"
  - "מטענים ומכולות"
  - "נמל יבשתי"
  - "השאלת עובדים"
  - "פיתוח עסקי"
  - "הפרדת תפקידים"
  - "הסכם הפרדה"
  - "שדה תעופה"
  - "החלטות ממשלה"
  - "תקציב"
  - "טיסות פנים"
  - "מנחתים"
  - "חוק הטיס"
  - "שירות לנוסע"
