bodies:
  - name: משרד המשפטים
  - name: רשות המסים
  - name: משטרת ישראל
  - name: הלשכה המרכזית לסטטיסטיקה
  - name: משרד הכלכלה
  - name: משרד ראש הממשלה
  - name: רשות האכיפה והגבייה
  - name: המועצה הישראלית לצרכנות
  - name: רשות להגנת הצרכן
